# Site settings
title: Ion
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "www.petermcgill.com" # the subpath of your site, e.g. /blog/
url: "http://petermcgill.com" # the base hostname & protocol for your site
twitter_username: petermcgill94
github_username:  petermcgill94

# Build settings
markdown: kramdown
